GreenScheduler/cats

- cats/api_query.py
- pyproject.toml
- tests/test_api_query.py
This is a simple way to cache the API request in a way that would be useable on a multi-user system. There are two 'bits'. First, we make the request for the 'top' of the half hour (so hh:00:00 or hh:30:00) by changing the current time before calling the API, then we make the call through requests_cache rather than requests. Because the time (and postcode) is
part of the request this means that old data is
reused, avoiding the HTTP call.
Currently the results are just in file `cats_cache.sqlits` in the current working directory, but we could put this in a hidden file in the users homespace, or in a global temporary directory or whatever.
At this stage think of this as a proof of concept. There are bits that need thinking about (where to put the cache, cleaning up the cache, install the …
> Caching of the HTTP call

- README.md
- cats/__init__.py
at(1) time syntax differs between macOS and Linux. Output the time
in MMDDhhmm format that can be passed to the POSIX standard -t option
which works across both.
This also updates the documentation to clarify that job duration
is in minutes and adds an example.
Fixes: #33, #34
> Modify output to be compatible with -t option of at(1)

- cats/__init__.py
- cats/api_interface.py
- cats/api_query.py
- tests/test_api_query.py
It is currently assumed that carbon intensity data comes from carbonintensity.org.uk. While it is likely to remain the case for a time (until we find data sources for other countries, see #22), it didn't seem a lot of effort -- and changes -- to abstract away the API-specific bits, namely:
- Getting a URL from a postcode and job runtime duration.
- Parsing the api response into a format usable by `cats` -- currently a list of tuples.
This PR add two new arguments `request_url_fun` and `parse_response_fun` to the `parsedata.get_tuple`:
```python
def get_tuple(
postcode: str,
request_url_fun: Callable[[datetime, str], str],
parse_response_fun: Callable[[dict], list[tuple[datetime, int]]],
) -> list[list[tuple[datetime, int]]]:
"""
get carbon intensity from a web API
"""
```
These two …
> Enable extension to other carbon intensity forecast providers

- cats/__init__.py
- cats/api_interface.py
- cats/api_query.py
- cats/forecast.py
- cats/parsedata.py
- cats/timeseries_conversion.py
- tests/test_api_query.py
- tests/test_timeseries_conversion.py
- tests/test_windowed_forecast.py
Currently the best start time estimate is obtained through calling a hierarchy of functions:
`parsedata.writecsv` -> `timeseries_conversion.cat_converter` -> `timeseries_conversion.get_lowet_carbon_intensity`.
The `writecsv` function writes the forecast data on disk, only for `cat_converter` to read it straight away. I think this was originally meant to be used as a cache, but as it stands it doesn't look to me like writing forecast data to disk is useful to anything else: an API request is made at each execution of `cats`, although since #30  the request itself is cached.
This PR sends forecast data directly to `get_lowest_carbon_intensity`, which is responsible for returning the best job start time and associated average carbon intensity. This reduces complexity by removing the multiple …
> Pass forecast data without writing csv to disk

- tests/test_windowed_forecast.py
This adds a couple of tests covering the `WindowsForecast` class. Checking that
- `min(WindowedForecast(data, job_duration))` correctly estimates the average intensity value and bounds of the best runtime period (minimal intensity).
- `WindowedForecast(data, job_duration)[0]` correctly estimates the average intensity value and bounds associated with starting the job at the time of running `cats`, i.e. without waiting for a better time window.
> Test use of `WindowedForecast`

- cats/CI_api_interface.py
- cats/CI_api_query.py
- cats/__init__.py
- cats/check_clean_arguments.py
- config.yml
This is a quick tidy-up of the different command line arguments available and their validation. The goal is to add hints and improve clarity for users, while also being consistent with the current project structure. 
- Drafted "help" text for all arguments (which would show with `-h` menu
- Moved the validation/cleaning of the location to `check_clean_arguments.py` 
- Added an argument to choose a CI API (or in the future, pass their own)
- small clean-up of the `validate_duration` function 
- small clean-up of `validate_jobinfo`
- Print out the values of different arguments (location, config used, CI API used etc.) to `stderr` to confirm values used to users (and simplify debugging for us!)
- Moved datetime 30min standardisation to the interface instead of the query (as this is interface …
> Tidy-up command line arguments

- cats/forecast.py
Streamlined the dataclasses `CarbonIntensityPointEstimate` and `CarbonIntensityAverageEstimate` by removing `sort_index`. As described in the SO discussion [here](https://stackoverflow.com/questions/68840767/what-is-the-purpose-of-sort-index-of-a-dataclass-in-python) this is only needed in specific cases, here we can simplify it by ordering the attributes (first attribute used for sorting).
> Remove sort_index from dataclass as not needed

- .github/workflows/docs-build-deploy.yml
- docs/docs-requirements.txt
This add a GitHub workflow to build the documentation website from sources in `docs/`. The built website is pushed to the `gh-pages` branch which can be used by GitHub to deploy the site.
In practice the documentation will be built and deployed each time commits are added to the `main`branch.
Somebody with elevated privileges (I think one of @andreww @c-martinez @tonymugen or @Llannelongue )should go into the repo settings and enable GitHub _Pages_ to be deployed from the root of the `gh-pages` branch. It's also important to check that Actions have read/write permissions (from the `Actions` section in the settings page).
> Deploy documentation automatically from `main`

- cats/CI_api_interface.py
- cats/optimise_starttime.py
- tests/test_api_query.py
- tests/test_windowed_forecast.py
This (draft) pull request makes sure we keep track of any differences in timezone between system time (e.g. used for `at`) and the time zone returned by our datasource. To do this, we need to:
With a little luck, the actual calculation will 'just work'. We should check this. 
This addresses #21
> Make sure we respect local system time

- cats/CI_api_query.py
- cats/__init__.py
- docs/README.md
Quick one to make some minor formatting updates, mostly for the command-line help descriptions (I went in to update the documentation README and thought I should include these updates), namely:
* instead of listing the documentation build requirements in the README, pointing to the new `docs-requirements.txt` file created in #60 so we don't have two equivalent lists to keep in sync;
* being more consistent in the command-line descriptions by, e.g., using only single quotes around all keywords (means the generated CLI reference emphasises them via italics but avoiding double quotes which will clutter the terminal `--help` output) and listing defaults at the end;
* adding default information for `--jobinfo` which was missing before, to be explicit and clear;
* capitalising the first word …
> Minor documentation updates for consistency and clarity

- cats/__init__.py
- cats/check_clean_arguments.py
- cats/configure.py
- docs/source/api-reference.rst
- tests/test_configure.py
The configuration for cats is specified by both a config file and cli arguments. Values provided at the command line often
override the values provided in the config file. It means there is a bit of work to be done in order to distil all that information into a fixed runtime configuration before cats can start making a request to a CI service. Namely, cats needs
- The location
- The APIInterface instance that prescribes how to contact the CI service
- The job duration
This PR moves the processing required to set these three things (the cats runtime configuration) into a separate module `configure` that provides a single `configure` function as an entry point. Benefits are:
- Less code in `__init__.py` which is starting get big
- Easier to add unit tests around the processing of config …
> Move processing of cli args and config file to separate module

- .github/workflows/tests.yml
- pyproject.toml
This will help us keep track of current test coverage - it's a simple change to the CI and dependancies. One thing to (maybe) think about is how these get reported (e.g. can we make github cache the previous coverage and use that to see if we are doing better). I'm happy for this to be merged or to leave it hanging around with more work needed.
> Have tests report coverage in CI

- .github/workflows/tests.yml
This will need somebody with admin access to set the `CODECOV_TOKEN` in GitHub Secrets from https://app.codecov.io/github/GreenScheduler/cats/settings
> ci: upload coverage to codecov

- README.md
- cats/__init__.py
- cats/config.yml
- docs/source/quickstart.rst
- pyproject.toml
- docs: link to generated Sphinx documentation #87
- docs: remove --jobinfo and create standalone config.yml
> Remove `--jobinfo`, standalone `config.yml` file

- .github/workflows/tests.yml
- cats/__init__.py
- cats/configure.py
- pyproject.toml
A reasonable amount to this, but it only (a) enabled type checking in our CI workflow and (b) makes this pass. It's a rebase of a previous PR with commits reorganised.
With the changes to get_runtime_config's return types, I think I agree with @tlestang that this is one of those places where type checking isn't really worth it. But if we don't do anything about it we cannot really do type checking elsewhere. I think (as I say in fb01f50dcc327b7c830b4cf07142dff16a76cc2d) that fact that we check `args.footprint` in two places isn't ideal (what if we rename the argument) but I wouldn't worry too much about that unless we actually want to further refactor. Anyway, I kept all of that in a single commit.
The other changes are (I think) pretty straightforward. I've incorporated the changes …
> Turn on static type checks in the CI (and have them pass)

- docs/source/quickstart.rst
At a glance, it looks like `--postcode` should be `--location`.
> Change CLI argument name in Quickstart documentation

- .github/workflows/tests.yml
- cats/CI_api_interface.py
- cats/configure.py
- cats/forecast.py
- tests/test_windowed_forecast.py
This fixes off-by-one errors in the code which led to #99. Detailed info is in commit messages.
> fix off by one

- .github/workflows/docs-build-deploy.yml
- cats/__init__.py
- docs/docs-requirements.txt
- docs/source/api-reference.rst
- docs/source/conf.py
- docs/source/installation.rst
- docs/source/quickstart.rst
- pyproject.toml
- Format config in example as a code block
- docs: fix typo
- Bump version to 1.0.0, add classifiers
> release v1

- cats/__init__.py
- docs/source/quickstart.rst
Minor updates to the CATS documentation, including:
* fix some typos appearing to the user. some misleading e.g. 'cpus' should be 'gpus' in the corresponding CLI argument description;
* clarify some statements which are somewhat misleading e.g. 'cats looks for a file named ``config.yaml`` in the current directory' when strictly it just needs a YAML extension so the same with `.yml` is also acceptable;
* update a code snippet implying that 'cats errors out' if no location is provided via CLI or configuration file, when actually at this stage CATS is more clever and will try to estimate location from the IP address.
Hopefully these are fairly self-explanatory suggestions, but please feel free to question.
> Update and clarify aspects in documentation

- cats/configure.py
- docs/source/quickstart.rst
- tests/test_configure.py
@aturner's PR #110 with merge conflict resolved and a test added
As previously:  Adds the option to set `CATS_CONFIG_FILE` environment variable to specify config file location. Config file location precedence becomes:
1. Command line option
2. Location specified in `CATS_CONFIG_FILE`
3. `./config.yaml`
> PR 110 redux

- cats/configure.py
We fall back to this API if the user (or configuration) does not provide a location. This caches the results. Note that this could be a problem for a laptop that moves between regions but in that case the power may well not be drawn from the grid anyway.
fixes #108
> Add caching to ipapi.co calls

- .pre-commit-config.yaml
- cats/__init__.py
- docs/source/use-with-schedulers.rst
- tests/test_main.py
- **ci: update pre-commit hooks**
- **feat: add sbatch scheduler support, fixes #122**
> 122 sbatch

- cats/__init__.py
Fixes issue #137 and displays the output of sbatch (e.g. "Submitted batch job 127"). 
It turns out that `at` displays the job number/status via stderr and that is what was causing it to appear on screen. `Sbatch` uses stdout, so this code captures and displays that output.
> Display sbatch output
